name: Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      TAG: ghcr.io/node-lambdas/core:${{ github.sha }}
      LATEST_TAG: ghcr.io/node-lambdas/core:latest

    steps:
      - uses: actions/checkout@v3

      - name: Add read-only token for GH packages registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_AUTH_TOKEN }}" >> _npmrc
          mv _npmrc .npmrc

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build code
        run: npm ci && npm run build

      - name: Build branch
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.TAG }}

      - name: Build latest
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
