name: Create and publish a cloud function

# Build and publish a Node function
# Requires at least an org and image name to work correctly.
# Usage:
#
# jobs:
#   build:
#     uses: node-lambdas/core/.github/workflows/fn.yml@main
#     with:
#       name: 'function-name'

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker pull ghcr.io/node-lambdas/core:latest
      - name: Create Dockerfile
        run: |
          echo 'FROM ghcr.io/node-lambdas/core:latest' > Dockerfile
          echo 'USER root' >> Dockerfile
          echo 'ADD . /home/node/app' >> Dockerfile
          echo 'RUN cd /home/node/app && npm i && (npm run build || true)' >> Dockerfile
          echo 'USER node' >> Dockerfile

          cat Dockerfile

      - name: Build latest tag
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/node-lambdas/${{ inputs.name }}:latest
